name: Debian ARM build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, Linux, ARM]
    
    # one day time out
    timeout-minutes: 1440
    
    steps:
    - uses: actions/checkout@v2
    - name: Check out submodules
      run: git submodule update --init --recursive
    - name: Build Emgu CV form debian ARM
      run: ./cmake_configure
      working-directory: ${{ github.workspace }}/platforms/debian/bullseye
    #- name: Build Emgu CV package binary
    #  run: make package
    #  working-directory: ${{ github.workspace }}/platforms/raspberry_pi_os/build/
    - uses: actions/upload-artifact@v2
      with:
        name: emgucv-debian-arm-zip-package
        path: ${{ github.workspace }}/platforms/debian/bullseye/build/*.zip
