name: Ubuntu build.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    # one day time out
    timeout-minutes: 1440
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    #- name: Check out submodules
    #  run: git submodule update --init --recursive
    - name: Build Emgu CV native binary
      run: ./cmake_configure
      working-directory: ${{ github.workspace }}/platforms/ubuntu/22.04
    - name: Build Emgu CV package binary
      run: make package
      working-directory: ${{ github.workspace }}/platforms/ubuntu/22.04/build/
    - uses: actions/upload-artifact@v3
      with:
        name: emgucv-ubuntu-zip-package
        path: ${{ github.workspace }}/platforms/ubuntu/22.04/build/*.zip
    - uses: actions/upload-artifact@v4
      with:
        name: emgucv-ubuntu-nuget-package
        path: ${{ github.workspace }}/platforms/nuget/*.nupkg 
